In [1]:
import numpy as np

In [3]:
a = np.arange(6)

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [15]:
b = np.array([1,55,11,2,87,4,5,23,87,10])
# b = b.reshape(5,2)

In [16]:
b

array([ 1, 55, 11,  2, 87,  4,  5, 23, 87, 10])

In [17]:
np.argsort(b)

array([0, 3, 5, 6, 9, 2, 7, 1, 4, 8], dtype=int64)

In [18]:
np.argmin(b)

0

In [20]:
np.argmax(b)

4