## Basic Functions

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5])

In [3]:
array1


array([1, 2, 3, 4, 5])

In [4]:
print(array1)

[1 2 3 4 5]


In [5]:
print(type(array1))

<class 'numpy.ndarray'>


In [6]:
array1.shape

(5,)

In [7]:
array1.dtype


dtype('int32')

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones(6).dtype

dtype('float64')

In [11]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
array1


array([1, 2, 3, 4, 5])

In [13]:
array1*array1


array([ 1,  4,  9, 16, 25])

## Slicing

In [14]:
array1[4:6]

array([5])

In [15]:
array1

array([1, 2, 3, 4, 5])

In [16]:
arr = array1[4:6]

In [17]:
arr

array([5])